FIX: "No max attemps" on show answers
eol-uchile/eol-dialogs-question-xblock pull request #10
Opened 2024-04-04 19:38 UTC by Lozamded

Se aplico una solucion al problema cuando se presiona mostrar respuesta sin que se haya ingresado el numero maximo de intentos

2024-04-15 19:02 UTC, tomaspemora requested changes
Sugiero dejar todo en un solo commit

2024-04-15 20:47 UTC, fsologureng requested changes

2024-04-15 20:47 UTC, fsologureng commented on dialogsquestionsxblock/dialogsquestionsxblock.py
> +            if (self.attempts >= self.max_attempts and self.show_answer == 'Finalizado') or self.show_answer == 'Mostrar':
La condición `self.show_answer == 'Finalizado'` está presente en ambas ramas del if-else viejo (el de más adentro).
Lo mismo ocurre con `self.show_answer == 'Mostrar'`, lo cual permite deducir que el return (que tb se repite idéntico en ambas condiciones) ya se alcanza cuando `self.show_answer == 'Mostrar'` es verdadera. Es decir, esta es una condición suficiente independiente de si `self.max_attempts` está definida o no.

Sugiero ordenar las prioridades de las condiciones para no evaluarlas de nuevo y dejar más claro qué se requiere para que el estado `Finalizado` permita retornar las respuestas.

2024-04-15 21:24 UTC, fsologureng commented on dialogsquestionsxblock/dialogsquestionsxblock.py
> +            if (self.attempts >= self.max_attempts and self.show_answer == 'Finalizado') or self.show_answer == 'Mostrar':
Por si acaso, después de una explicación de @tomaspemora sobre el error que se intenta corregir, para evitar la variable indefinida en la comparación, se suele resolver así:
```
( (self.max_attempts is None or self.attempts >= self.max_attempts) and self.show_answer == 'Finalizado') or self.show_answer == 'Mostrar'
```

2024-04-23 15:27 UTC, tomaspemora commented
lo veo bien @fsologureng. Que opinas?

2024-04-23 16:07 UTC, fsologureng commented
> lo veo bien @fsologureng. Que opinas?

Sí. tb lo veo bien.

2024-04-23 16:07 UTC, fsologureng approved these changes

2024-04-23 16:40 UTC, merged